services:
  webpack:
    build:
      context: .
      dockerfile: ./infra/development/webpack/Dockerfile
    volumes:
      - type: bind
        source: ./laravel
        target: /var/www/html
      - type: volume
        source: node_modules
        target: /var/www/html/node_modules
    ports:
      - "38080:8080"
  nginx:
    build: ./infra/development/nginx
    volumes:
      - ./laravel:/var/www/html
      - ./infra/development/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "48080:80"
  app:
    build: ./infra/development/php
    volumes:
      - ./laravel:/var/www/html
  db:
    build:
      context: .
      dockerfile: ./infra/development/mysql/Dockerfile
    volumes:
      - db-store:/var/lib/mysql
      # gptより
      # - ./infra/development/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./infra/development/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "43306:3306"

volumes:
  node_modules:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/laravel/node_modules
      o: bind
  db-store:
