FROM mysql:8.0

ENV MYSQL_ROOT_PASSWORD=password
# initでやってるからいらなくなったかも
# ENV MYSQL_DATABASE=laravel \
#     MYSQL_USER=php \
#     MYSQL_PASSWORD=password


# gptより
# COPY ./infra/development/mysql/my.cnf /etc/my.cnf

EXPOSE 3306
